name: Format
on: pull_request
jobs:
  format:
    if: ${{ github.repository_owner == 'mskelton' }}
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
        with:
          ref: ${{ github.head_ref }}
      - run: yarn format
      - run: yarn lint --fix || exit 0
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
